### ISSUE TITLE
Crash. node_ on_receive_fields()

### ISSUE THREAD

**Issue by amadin** [kilbith/xdecor#21] opened 2016-01-10 08:36 UTC
2016-01-10 03:30:27: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix t
he following error:
2016-01-10 03:30:27: ERROR[main]: Lua: Double fault error from mod 'xdecor' in callback node_
on_receive_fields(): error in error handling

In thread 7f21b76c0780:
/home/user/minetest/src/server.cpp:511: void Server::step(float): A fatal error occurred: Lua
: Double fault error from mod 'xdecor' in callback node_on_receive_fields(): error in error h
andling
Debug stacks:
DEBUG STACK FOR THREAD 7f21aabfd700:
#0  virtual void* EmergeThread::Thread()
(Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f21ab5fe700:
#0  virtual void* CurlFetchThread::Thread()
DEBUG STACK FOR THREAD 7f21abfff700:
#0  virtual void* ServerThread::Thread()
#1  void Server::Receive()
(Leftover data: #2  virtual void Server::deletingPeer(con::Peer*, bool))
(Leftover data: #3  void RemoteClient::GetNextBlocks(ServerEnvironment*, EmergeManager*, floa
t, std::vector<PrioritySortedBlockTransfer>&))
(Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
(Leftover data: #5  bool getCraftingResult(Inventory*, ItemStack&, std::vector<ItemStack>&, b
ool, IGameDef*))
(Leftover data: #6  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
(Leftover data: #7  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f21b76c0780:
#0  int main(int, char**)
#1  Dedicated server branch
#2  void dedicated_server_loop(Server&, bool&)
#3  void Server::step(float)
(Leftover data: #4  void Server::SendAccessDenied_Legacy(irr::u16, const wstring&))

Mod updated ~ 24 hours ago. 0.4.13 stable with minetest_game development version. 93.170.76.99

Mods:

serveressentials
protection_lagporter
no_sneak_glitch
home_gui
daynight
chat2
advancedban
craft_guide
default
workbench
torches
mobs
fake_fire
compassgps
columnia
caverealms
boost_cart
xpanes
wool
lrfurn
boats
beds
farming
potions
stairs
darkage
vessels
tnt
give_initial_stuff
flowers
ethereal
creative
bucket
inventory_plus
skins
3d_armor
playeranim
wieldview
technic_armor
shields
hud
hunger
screwdriver
doors
xdecor
protector
dye

**Comment by kilbith** [comment] 2016-01-10 10:29
Give me the actions log before the crash.

**Comment by amadin** [comment] 2016-01-10 10:35
I don't used action logging, only error logging. I use only Enchant Table, Mailbox and Hive from xdecor which can use on_receive_fields.

**Comment by kilbith** [comment] 2016-01-10 10:43
That won't help me much if you don't give me steps to reproduce...

Try to update again maybe ?

**Comment by amadin** [comment] 2016-01-10 10:48
Ok i will try tomorrow

**Comment by kilbith** [comment] 2016-01-12 11:31
Closing since I have no more informations...

Next time indicate clear steps to reproduce your issue, please.

**Closed by kilbith** 2016-01-12 11:31 UTC

**Comment by amadin** [comment] 2016-01-12 11:32
Ok, after update i don't get crashes.
